version: '3.8'

services:
  webapi:
    build:
        context: .
    ports:
      - "8080:8080"
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: toDoDB
    ports:
      - "3307:3306"
    volumes:
      - ./ExampleData.sql:/docker-entrypoint-initdb.d/ExampleData.sql